name : "Deploy to azure app service"
on :   
  push: 
    branches : [master]
  pull_request:
    branches : [master]
    
jobs:
  Build :
    runs-on : ubuntu-latest
    env:
      AZURE_WEBAPP_PACKAGE_PATH: '.'
      AZURE_WEBAPP_NAME: Demo

    steps:
    
    - uses: actions/checkout@v2
    
    - name : "Setup dotnet"
    - uses : actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name : "Restore packages"
      run : dotnet restore
      
    - name : "build the code"
      run : dotnet build --configuration Release
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
  
