name: 'Deploy to Azure App Service using spn'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop
    paths:
      - '**'
      - '!Documentation/**'
  
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  
jobs:
  Build:
    runs-on: ubuntu-latest
    # environment : development
    steps:
    - uses: actions/checkout@v2    
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
     
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
      
    - name: Upload artifacts for deployment
      uses: actions/upload-artifact@v2
      with:
        name: sampleapp
        path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
        
  Deploy_Development:    
    runs-on: ubuntu-latest
    needs: Build
    environment : development
    if: ${{ github.event_name != 'pull_request' }}
    
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: sampleapp
        
    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using spn'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ vars.AZURE_WEBAPP_NAME }} 
        package: .
        
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}
        app-settings-json: '${{ vars.APP_SETTINGS }}' 
      
    - name: logout
      run: |
        az logout
        
  Deploy_Production:     
    runs-on: ubuntu-latest
    needs: [Build, Deploy_Development]
    environment : production
    if: ${{ github.ref == 'refs/heads/master' and github.event_name != 'pull_request' }}
        
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: sampleapp
        
    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using spn'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ vars.AZURE_WEBAPP_NAME }} 
        package: .
        
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}
        app-settings-json: '${{ vars.APP_SETTINGS }}' 
      
    - name: logout
      run: |
        az logout
        
