name: 'Deploy to Azure App Service using spn'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**'
      - '!Documentation/**'
  
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  AZURE_WEBAPP_NAME: sampleapp44

jobs:
  Build:
    runs-on: ubuntu-latest
    # environment : development
    steps:
    - uses: actions/checkout@v2    
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
     
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Publish
      run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
      
    - name: Upload artifacts for deployment
      uses: actions/upload-artifact@v2
      with:
        name: sampleapp
        path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
        
  Deploy:     
    runs-on: ubuntu-latest
    needs: Build
    environment : development
    
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Downlod artifacts
      uses: actions/download-artifact@v2
      with:
        name: sampleapp
        
    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        package: .
        
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        app-settings-json: '${{ vars.APP_SETTINGS_VAR }}' 
      
    - name: logout
      run: |
        az logout
